### ISSUE TITLE
Use maps metadata in new lobby

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/maps-metadata#30]
Basic integration of pulling information from this repo to new lobby to show list of current mapts. The portion that belongs in this repo is to figure out the schema of data as needed by new lobby and write a script that generates it.

**Comment by ElMorrisonAsWell** [comment]
Hey there! I'm interested in looking into this issue as my first contribution. @thehobojoe Have you made progress on this yet? Because I would like to start familiarizing myself with this repo/issue and the new lobby's mapbrowser and I would be grateful for any pointers!

**Comment by p2004a** [comment]
I've unassigned him because he is not working on it at the moment.

For new lobby, on discord there is video how to get started. I assume new lobby will use this API https://github.com/beyond-all-reason/maps-metadata/blob/main/cloud/serving/README.md to fetch generated content, images etc. For how to add new files there, see various `gen_` files in https://github.com/beyond-all-reason/maps-metadata/tree/main/scripts/js/src, [`gen_live_maps.ts`](https://github.com/beyond-all-reason/maps-metadata/blob/main/scripts/js/src/gen_live_maps.ts) is the simplest, output served like: https://maps-metadata.beyondallreason.dev/latest/live_maps.validated.json. For the most comprehensive usage of extracting different pieces of map metadata, you can check out [how this object](https://github.com/beyond-all-reason/maps-metadata/blob/a9341618be95fb798e27fbabd9992df35ffdd54f/scripts/js/src/sync_to_webflow.ts#L469-L495) is built for the website.

So IMHO the steps are:
1. Define the JSON schema(s?) for how lobby will consume the maps metadata.
2. Write generator in this repo.
3. Integrate fetching of this metadata in new lobby from the API

**Comment by ElMorrisonAsWell** [comment]
Thanks for the pointers! I'll be taking a closer look this evening, I'll check back when I've made some progress/questions come up.

**Comment by bcdrme** [comment]
Alright so I think something like would allow us to have the same features as https://www.beyondallreason.info/maps
Preview images would be 1K (1024x1024 pixels, or any combination, jpg, 70% quality).

`tags`, I don't think we have in rowy but it would be very useful.

```json 
[
  {
    "authors": "Nikuksis",
    "certified": true,
    "description": "Descending lava will open the ways to the opposite site.",
    "displayName": "Thermal Shock",
    "images": {
      "preview": "https://springfiles.com/sites/default/files/maps/thermal_shock_v1.1.jpg"
    },
    "mapLists": [
      "ladder1v1",
      "popular16p",
      "land16p",
      "fightNight12",
      "superTournament25"
    ],
    "playerCountMin": 12,
    "playerCountMax": 16,
    "springName": "Thermal Shock v1.1",
    "startPos": {
      "positions": {
        "P1": {
          "x": 1302,
          "y": 494
        },
        "P10": {
          "x": 9228,
          "y": 7153
        },
        "P11": {
          "x": 7276,
          "y": 8924
        },
        "P12": {
          "x": 7994,
          "y": 7199
        },
        "P13": {
          "x": 6339,
          "y": 7214
        },
        "P14": {
          "x": 5681,
          "y": 8899
        },
        "P15": {
          "x": 4579,
          "y": 7574
        },
        "P16": {
          "x": 4083,
          "y": 9336
        },
        "P2": {
          "x": 3140,
          "y": 1036
        },
        "P3": {
          "x": 1659,
          "y": 2249
        },
        "P4": {
          "x": 3158,
          "y": 2189
        },
        "P5": {
          "x": 2882,
          "y": 3846
        },
        "P6": {
          "x": 979,
          "y": 4062
        },
        "P7": {
          "x": 2447,
          "y": 5574
        },
        "P8": {
          "x": 919,
          "y": 6166
        },
        "P9": {
          "x": 9751,
          "y": 8985
        }
      },
      "teamsSet": [
        {
          "playersPerTeam": 8,
          "sides": [
            {
              "starts": [
                {
                  "role": "air",
                  "spawnPoint": "P1"
                },
                {
                  "role": "front",
                  "spawnPoint": "P2"
                },
                {
                  "role": "front/tech",
                  "spawnPoint": "P3"
                },
                {
                  "role": "front",
                  "spawnPoint": "P4"
                },
                {
                  "role": "front",
                  "spawnPoint": "P5"
                },
                {
                  "role": "front",
                  "spawnPoint": "P6"
                },
                {
                  "role": "front",
                  "spawnPoint": "P7"
                },
                {
                  "role": "front",
                  "spawnPoint": "P8"
                }
              ]
            },
            {
              "starts": [
                {
                  "role": "air",
                  "spawnPoint": "P9"
                },
                {
                  "role": "front",
                  "spawnPoint": "P10"
                },
                {
                  "role": "front/tech",
                  "spawnPoint": "P11"
                },
                {
                  "role": "front",
                  "spawnPoint": "P12"
                },
                {
                  "role": "front",
                  "spawnPoint": "P13"
                },
                {
                  "role": "front",
                  "spawnPoint": "P14"
                },
                {
                  "role": "front",
                  "spawnPoint": "P15"
                },
                {
                  "role": "front",
                  "spawnPoint": "P16"
                }
              ]
            }
          ],
          "teamCount": 2
        }
      ]
    },
    "startPosActive": true,
    "startboxesSet": [
      {
        "maxPlayersPerStartbox": 8,
        "startboxes": [
          {
            "poly": [
              {
                "x": 80,
                "y": 140
              },
              {
                "x": 200,
                "y": 200
              }
            ]
          },
          {
            "poly": [
              {
                "x": 0,
                "y": 0
              },
              {
                "x": 60,
                "y": 120
              }
            ]
          }
        ]
      }
    ],
    "terrain": ["flat", "hills", "lava", "wasteland"],
    "mapWidth": 20,
    "mapHeight": 20,
    "windMin": 4,
    "windMax": 16,
    "tidal": 0,
    "tags": ["5V5", "6V6", "7V7", "8V8", "FFA", "PVE"]
  }
]

```

**Comment by p2004a** [comment]
Resolved in #422, information is published at https://maps-metadata.beyondallreason.dev/latest/lobby_maps.validated.json, schema in https://github.com/beyond-all-reason/maps-metadata/blob/main/schemas/lobby_maps.yaml

**Comment by bcdrme** [comment]
Slight issue with the images @p2004a 
They have a .jpg extension in URL but they really are an `image/webp`.

Also, but I don't know if anything can be done about it:

If I compare what I had
https://firebasestorage.googleapis.com/v0/b/rowy-1f075.appspot.com/o/maps%2FMuFsIEswFS9FbuamCfbS%2Fphoto%2FIDnsPXeTVxsS53VCpDD2-shore-to-shore-minimap.jpg?alt=media&token=00476553-8caf-47cd-af35-e9330cb52bf6

With 
https://maps-metadata.beyondallreason.dev/i/fit-in/1024x1024/filters:format(webp):quality(75)/rowy-1f075.appspot.com/maps/MuFsIEswFS9FbuamCfbS/photo/IDnsPXeTVxsS53VCpDD2-shore-to-shore-minimap.jpg

Both have less than 1024x1024 pixels but the later has a lot less pixels because of the fit-in limiting the width of the image to 1024 pixels.

**Comment by p2004a** [comment]
Yes, I'm returning webp as indicated in the format, why does it have to be a less efficient jpeg?

Yes, I'm bounding the image to fit in (as indicated in the filter), 1024x1024 box, what other scaling do you need?

For full filter syntax please take a look at: https://github.com/cshum/imagor I can also just return url with a hole to put whatever filters you want instead of returning final full url.

**Comment by bcdrme** [comment]
I find it odd that the file extension doesn't match the content type, but maybe it's normal as maybe it is a reference to the original file ? 

Yup nothing in the api does what I had in mind, but it's ok. Also if we need a higher res we can just add another image url in the metadata 👍

**Comment by p2004a** [comment]
> I find it odd that the file extension doesn't match the content type, but maybe it's normal as maybe it is a reference to the original file ?

Yes, it's just reference. It's also quite normal, just like e.g. `.gif` online was often just `.mp4`. It's possible for CTRL+S to work and safe with correct extension, but I've not bothered to do it.

> Nothing in the api does what I had in mind, but it's ok. Also if we need a higher res we can just add another image url in the metadata 👍

What exactly did you needed?

Also what about

> I can also just return url with a hole to put whatever filters you want instead of returning final full url.

?

**Comment by bcdrme** [comment]
I don't know what's needed tbh. I can only speculate that a bigger resolution might be needed when the map is maximized. But we need to review the client first, challenge current design, and if we need some changes to this metadata project, I'll report back here.

What you suggest is nice for flexibility but standby for now. It's already great as is 👍

**Comment by p2004a** [comment]
> bigger resolution might be needed when the map is maximized

Note that we request from Mappers at least 1024 at the longest side of map photo, so higher resolution pictures simply won't be available for many maps. The shot is from in-game, if you have only low resolution monitor e.g. 1920x1080, and map that is square, 1024 it barely what you can do with a simple screenshot.

So, if we need higher resolution e.g. 2048x2048, or minimal length on shortest dimension be 1024, plenty, almost all, of map photos will need to be retaken.

---

As for this GitHub issue, I will close this as resolved. If any other dimensions are needed, it mostly should be simple change in https://github.com/beyond-all-reason/maps-metadata/blob/main/scripts/js/src/gen_lobby_maps.ts.
