### ISSUE TITLE
Integrate into BAR website

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/maps-metadata#32]
Website is in webflow, so need to figure out how to best integrate with it.

It needs to go through the repo so that approval workflow works as intended.

**Comment by icexuick** [comment]
https://developers.webflow.com/reference/list-items
https://developers.webflow.com/reference/create-item
https://developers.webflow.com/reference/publish-items

**Comment by p2004a** [comment]
Tested, and looks to work, so marking this as resolved 🎉
